name: Install App
description: Installs Node, pnpm, and app dependencies
runs:
  using: "composite"
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v3
      with:
        version: 8
    - name: Install Node
      uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
      with:
        node-version-file: '.nvmrc'
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install
      shell: bash