name: Install App
description: Installs Node, pnpm, and app dependencies
runs:
  using: "composite"
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v3
      with:
        version: 8
    - name: Install Node
      uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
      with:
        node-version-file: '.nvmrc'
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install
      shell: bash