extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:svelte/recommended
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
  - '@stylistic/'
parserOptions:
  project: ./tsconfig.json
  extraFileExtensions:
    - .svelte
env:
  browser: true
overrides:
  - files: 
    - '*.svelte'
    parser: svelte-eslint-parser
    parserOptions:
      parser: '@typescript-eslint/parser'
ignorePatterns:
  - /*
  - '!/src'
rules:
  'no-console':
    - error
  '@typescript-eslint/no-unused-vars':
    - error
    - argsIgnorePattern: '^_'
      varsIgnorePattern: '^_'
      caughtErrorsIgnorePattern: '^_'
  '@stylistic/semi':
    - warn
    - always
  '@stylistic/quotes':
    - warn
    - single
  'svelte/html-quotes':
    - warn
    - prefer: double