name: Node.js CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: ./.github/workflows/scripts/install
    - name: Lint
      run: pnpm run lint
  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    steps:
    - uses: ./.github/workflows/scripts/install
    - name: Typecheck
      run: pnpm run check
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
    - uses: ./.github/workflows/scripts/install
    - name: Unit tests
      run: pnpm run test:single